#!/bin/sh

ROOT="/mnt/root"
ROOT_DEV="/dev/mmcblk0p2"

# mount temporary filesystems
mount -n -t devtmpfs devtmpfs /dev
# mount -n -t proc     proc     /proc
# mount -n -t sysfs    sysfs    /sys
# mount -n -t tmpfs    tmpfs    /run

# mount new root
[ -d ${ROOT} ] || mkdir -p ${ROOT}
mount ${ROOT_DEV} ${ROOT}

# Copy linker & kernel modules
cp -r /lib/* ${ROOT}/nybble/lib

# switch to new rootfs and exec init
cd ${ROOT}
exec switch_root . "/nybble/boot/init"